config/routes.rb
Rails.application.routes.draw do
  resources :departments

  resources :employees

  resources :companies

  resources :vendors
  get 'sandbox/job_results'
  get 'tasks/mark_as_complete'
  get 'tasks/mark_as_incomplete'
  resources :categories
  resources :tasks
  resources :announcements

  devise_for :users, controller: {registrations: 'registrations'}
  resources :clients
  resources :projects

root to: "clients#index"
  

  get 'sandbox/clients'
  get 'sandbox/projects'
  get 'say/hello'
  get 'say/goodbye'
  get 'say/products'
  get 'sandbox/tasks'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
        if user.role == "admin"
            can [:read], [Client, Project, Task]
            can :manage, [Vendor]
            can [:hello , :goodbye], :say
             elsif user.role == "users"
            can :manage, [Client, Project, Task]
            can [:hello], :say
        elsif user.role == "vendor"
            can :manage, [Vendor]
            can :read, [Client]
        end
    end
end            
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities

app/models/announcement.rb
class Announcement < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :project_categories
	has_many :projects, through: :project_categories

	validates :name, presence: true
	#validates_presence_of :name

	
end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many :projects
	belongs_to :user

	before_create :generate_client_code

	validates_presence_of :name, :copany, :mobile, :email
	validates_length_of :mobile, is: 10
	validates_numericality_of :mobile
	validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
	validates_uniqueness_of :mobile, :email, scope: :user_id

	#client = Client.first
#client.projects
#this will returns an array of projects belonging to the clients

#project = project.first
#project.client.name
#this will return the name of the client, it returns and error if project's client_id is nil






	def details
		"#{self.name} - #{self.copany} - #{self.mobile} - #{self.email} "
	end

	def list_projects
		Project.where('client_id = ?', self.id)
	end

	def list_by_status(status)
		Project.where('client_id = ? AND status = ?', self.id, status)
	end

	
	def generate_client_code
		self.code = "#{self.name[0..2]} - #{Client.last.nil? ? 1 : Client.last.id + 1}"
	end
end

app/models/company.rb
class Company < ActiveRecord::Base
	validates :name, :email, :address, presence: true

	has_many :employees
end

app/models/department.rb
class Department < ActiveRecord::Base
	validate :name, peresence: true

	has_many :employees
end

app/models/employee.rb
class Employee < ActiveRecord::Base
	validates :first_name, :last_name, :company_id, presence: true

	belongs_to :company
	belongs_to :department
	before_create :generate_employee_code

	def generate_employee_code
		self.employees_code = "#{self.first_name[0..2]} - #{Employee.last.nil? ? 1 : Employee.last.id + 1} "
	end
end

app/models/project.rb
class Project < ActiveRecord::Base
	#has_many :join_table
	#has_many :associated_table, through: :jojn_table

	has_many :project_categories
	has_many :categories, through: :project_categories 



	belongs_to :client
	has_many :tasks
	belongs_to :user

	validates_presence_of :name, :description, :start_date, :end_date, :client_id, :budget, :status
	validates_length_of :description, minimum: 10
	validates_numericality_of :client_id

	#customer validations
	validate :check_date
	before_destroy :destroy_all_tasks

	def self.new_projects
		Project.where('status = ?', "new")
	end

	def iscompleted_tasks
		self.tasks.where('is_completed = ?' , true)
	end
	def incompleted_tasks
		self.tasks.where('is_completed = ?' , false)
	end




	private
	def destroy_all_tasks
		self.tasks.each do |task|
			task.destroy
	 	#Task.where('project_id = ?' , self.id).delete_all
	end

	def check_date
		if (!self.end_date.nil? && !self.start_date.nil?) && (self.end_date <= self.start_date)
			errors.add(:end_date, "should be greater than the start date")
		end
	end
end

	def details
		"#{self.name} - #{self.description} - #{self.status}"
	end
end

app/models/project_category.rb
class ProjectCategory < ActiveRecord::Base
	belongs_to :project
	belongs_to :category
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :project


	validates_presence_of :title
	

	#validate :check_valid_date  # if !self.project.nil?

	#private
	#def check_valid_date
	
	#	if (self.due_date < self.project.start_date || self.due_date > self.project.end_date)
	#		errors.add(:due_date, "is invalid")
	#	end
	#end

	#def check_boolean
	#	if !([true,false].include? self.is_completed)
	#		errors.add(:is_completed, "should be either true or false")
	#	end
	#end
	

	def details
		"#{self.title} - #{self.project_id} - #{self.due_date} - #{self.is_completed}"
	end
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :clients
	has_many :projects
	has_many :categories
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


	 def is_admin?
	 	return true if self.role == "admin"
	end
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

	before_filter :authenticate_user!
	load_and_authorize_resource
	def index
		@clients = current_user.is_admin? ? Client.all : current_user.clients
	end
	def new 
		@client = Client.new
	end
	def create
		@client = Client.new(client_params)
		@client.user_id = current_user.id
		if @client.save
			redirect_to clients_path
		else
			render action: "new"
		end
	end

	def show
		begin
		@client = current_user.is_admin? ? Client.find(params[:id]) : current_user.clients.find(params[:id])
	rescue ActiveRecord::RecordNotFound
		redirect_to clients_path, notice: "Record Not Found"
	end
end
	def edit
		@client = Client.find(params[:id])
	end
	def update
		@client = Client.find(params[:id])
		@client.user_id = current_user.id
		if @client.update_attributes(client_params)
			redirect_to client_path(@client.id), notice: "Successfully updated"
		else 
			render action: "edit"
		end
	end
	def destroy
		@client = Client.find(params[:id])
		@client.destroy
		redirect_to clients_path, notice: "Successfull deleted #{@client.name}"
	end
	
	private
	def client_params
		params[:client].permit(:name, :copany, :email, :mobile)
	end
		

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sandbox_helper.rb
module SandboxHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/clients/_form.html.erb
<%= form_for @client do |f| %>

<% if @client.errors.any? %>
		<h4>These errors prohibited the form from being saved: </h4>
			<ul style="color:red;">
				<% @client.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
	<% end %>
	</ul>
<% end %>


<div class="form-group">
	<label>Name</label><br/>
	<%= f.text_field :name, class: "form-control" %><br/>
</div>


<div class="form-group">
	<label>Company</label><br/>
	<%= f.text_field :copany, class: "form-control" %><br/>
</div>


<div class="form-group">
	<label>Mobile</label><br/>
	<%= f.text_field :mobile, class: "form-control" %><br/>
</div>


<div class="form-group">
	<label>Email</label><br/>
	<%= f.email_field :email, class: "form-control" %><br/>
</div>

	<%= f.submit "Submit", class: "btn btn-primary" %> or <%= link_to "back", clients_path %>
	<% end %>  

app/views/clients/edit.html.erb
<div class="row" >
	<div class="col=md-8" >
		<div class="page-header">
			<h2>Edit Client</h2>
		</div>
		<%= render 'form' %>
	</div>
</div>

app/views/clients/index.html.erb
<h1><%= notice %></h1>

<div class="row">
<div class="col-md-8">

<div class="page-header">
<h3> Listing Clients </h3>
</div>
<%= link_to clients_path(format: "xls"), class: "btn btn-info btn-sm pull-right" do %>
<span class="glyphicon glyphicon-download" ></span> Export to Excel
<% end %>


<script>
$(document).ready(function(){
    $('#myTable').DataTable();
});
</script>


<br/><br/>

<% if @clients.empty? %>
<p>No Clients Found </p>
<% else %>

<table class="table table-stiped" id="myTable">
<thead>
<tr>
<th>#</th>
<th>Name</th>
<th>Company</th>
<th>Mobile</th>
<th>Email</th>
	<% if current_user.is_admin? %>
		<th> User </th>
	<% end %>
<th>Action</th>
<th>Project Count</th>

</tr>
</thead>
<tbody>
<% @clients.each_with_index do |client,index| %>
<tr>
<td><%= index + 1%></td>
<td><%= link_to client.name.capitalize, client_path(client.id) %></td>
<td><%= client.copany %></td>
<td><%= client.mobile %></td>
<td><%= client.email %></td>
	<% if current_user.is_admin? %>
		<td><%= client.user.email %></td>
	<% end %>
<td><%= link_to client_path(client.id) do %>
<span class="glyphicon glyphicon-hand-right"></span>
<% end %>
</td>

<td><%= (client.projects).count %></td>
</tr>
<% end %>
</tbody>
</table> 
<% end %>


<% if can? :create, Client.new %>
<%= link_to "Add Client", new_client_path, class: "btn btn-success" %> 
<% end %>


</div>


	<div class="col-md-4">
		<div class="page-header">
			<h3> Statistics </h3>
		</div>
		<% data = {}
		current_user.clients.each do |client|
			data[client.name] = client.projects.count
		end
		%>
		<%= data %>
		<%= pie_chart(data) %>
		<%= column_chart(data) %>
		<%= bar_chart(data) %>




	</div>
</div>

app/views/clients/index.xls.erb
<h1>Client Details</h1>

<table border="1">
<thead>
<tr>
<th>#</th>
<th>Name</th>
<th>Company</th>
<th>Mobile</th>
<th>Email</th>
<th>Action</th>
<th>Project Count</th>

</tr>
</thead>
<tbody>
<% @clients.each_with_index do |client,index| %>
<tr>
<td><%= index + 1%></td>
<td><%= link_to client.name.capitalize, client_url(client.id) %></td>
<td><%= client.copany %></td>
<td><%= client.mobile %></td>
<td><%= client.email %></td>
<td><%= link_to "Show", client_url(client.id) %>

<td><%= (client.projects).count %></td>
</tr>
<% end %>
</tbody>
</table> 

app/views/clients/new.html.erb
<div class="row" >
	<div class="col=md-8" >
		<div class="page-header">
			<h2>Add Client</h2>
		</div>
		<%= render 'form' %>
	</div>
</div>

app/views/clients/show.html.erb
<div class="row">
	<div class="col=md-7">
		<div class="page-header">
		<h2><%= @client.name %><br/>
		<small>
			<span class="glyphicon glyphicon-briefcase"></span><%= @client.copany %>
			<span class="glyphicon glyphicon-earphone"></span><%= @client.mobile %>
			<span class="glyphicon glyphicon-envelop"></span><%= mail_to @client.email %>
			<%= @client.code %>
			</small></h2>
		</div>
	</div>

	<div class="panel panel-primary">
		<div class="panel-heading">Projects</div>
			<div class="panel-body">
				<ul class="list-group">
					<% for project in@client.projects %>
						<li class="list-group-item"><%= project.name %></li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>




	<div class="col-md-5">
				
	</div>
</div>


<%= link_to "edit" , edit_client_path(@client.id) %> | 
			<%= link_to "destroy", client_path(@client.id), data: {method: :delete, confirm: "Are you sure?"} %>

			<% if @client.projects.empty? %>
			No Project Found
			<% else %>
			<h3> Total Projects: <%= @client.projects.size %></h3>
			<ul>
			<% @client.projects.each do |project| %>
			<li><%= link_to project.name, project_path(project.id) %></li>
			<% end %>
			</ul>
			<% end %>

<div class="row">
	<div class="col-md-12">
		<div class="page-header" >
			<h2>Time line</h2>
							<% data = []
				@client.projects.each do |project|
					data.push([project.name, project.start_date,project.end_date])
				end
				%>
				<%= timeline(data) %>


				<h4> Total Tasks for this client is :
				<p> Inner Join </p>
					<%= Task.joins(:project).where('projects.client_id = ?', @client.id).size %>
					</h4>


				<h4><p> Select in </p></h4>
				<%= Task.where(project_id: @client.project_ids).size %>

		</div>
	</div>
</div>