config/routes.rb
Rails.application.routes.draw do
  resources :departments

  resources :employees

  resources :companies

  resources :vendors
  get 'sandbox/job_results'
  get 'tasks/mark_as_complete'
  get 'tasks/mark_as_incomplete'
  resources :categories
  resources :tasks
  resources :announcements

  devise_for :users, controller: {registrations: 'registrations'}
  resources :clients
  resources :projects

root to: "clients#index"
  

  get 'sandbox/clients'
  get 'sandbox/projects'
  get 'say/hello'
  get 'say/goodbye'
  get 'say/products'
  get 'sandbox/tasks'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
        if user.role == "admin"
            can [:read], [Client, Project, Task]
            can :manage, [Vendor]
            can [:hello , :goodbye], :say
             elsif user.role == "users"
            can :manage, [Client, Project, Task]
            can [:hello], :say
        elsif user.role == "vendor"
            can :manage, [Vendor]
            can :read, [Client]
        end
    end
end            
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities

app/models/announcement.rb
class Announcement < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :project_categories
	has_many :projects, through: :project_categories

	validates :name, presence: true
	#validates_presence_of :name

	
end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many :projects
	belongs_to :user

	before_create :generate_client_code

	validates_presence_of :name, :copany, :mobile, :email
	validates_length_of :mobile, is: 10
	validates_numericality_of :mobile
	validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
	validates_uniqueness_of :mobile, :email, scope: :user_id

	#client = Client.first
#client.projects
#this will returns an array of projects belonging to the clients

#project = project.first
#project.client.name
#this will return the name of the client, it returns and error if project's client_id is nil






	def details
		"#{self.name} - #{self.copany} - #{self.mobile} - #{self.email} "
	end

	def list_projects
		Project.where('client_id = ?', self.id)
	end

	def list_by_status(status)
		Project.where('client_id = ? AND status = ?', self.id, status)
	end

	
	def generate_client_code
		self.code = "#{self.name[0..2]} - #{Client.last.nil? ? 1 : Client.last.id + 1}"
	end
end

app/models/company.rb
class Company < ActiveRecord::Base
	validates :name, :email, :address, presence: true

	has_many :employees
end

app/models/department.rb
class Department < ActiveRecord::Base
	validate :name, peresence: true

	has_many :employees
end

app/models/employee.rb
class Employee < ActiveRecord::Base
	validates :first_name, :last_name, :company_id, presence: true

	belongs_to :company
	belongs_to :department
	before_create :generate_employee_code

	def generate_employee_code
		self.employees_code = "#{self.first_name[0..2]} - #{Employee.last.nil? ? 1 : Employee.last.id + 1} "
	end
end

app/models/project.rb
class Project < ActiveRecord::Base
	#has_many :join_table
	#has_many :associated_table, through: :jojn_table

	has_many :project_categories
	has_many :categories, through: :project_categories 



	belongs_to :client
	has_many :tasks
	belongs_to :user

	validates_presence_of :name, :description, :start_date, :end_date, :client_id, :budget, :status
	validates_length_of :description, minimum: 10
	validates_numericality_of :client_id

	#customer validations
	validate :check_date
	before_destroy :destroy_all_tasks

	def self.new_projects
		Project.where('status = ?', "new")
	end

	def iscompleted_tasks
		self.tasks.where('is_completed = ?' , true)
	end
	def incompleted_tasks
		self.tasks.where('is_completed = ?' , false)
	end




	private
	def destroy_all_tasks
		self.tasks.each do |task|
			task.destroy
	 	#Task.where('project_id = ?' , self.id).delete_all
	end

	def check_date
		if (!self.end_date.nil? && !self.start_date.nil?) && (self.end_date <= self.start_date)
			errors.add(:end_date, "should be greater than the start date")
		end
	end
end

	def details
		"#{self.name} - #{self.description} - #{self.status}"
	end
end

app/models/project_category.rb
class ProjectCategory < ActiveRecord::Base
	belongs_to :project
	belongs_to :category
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :project


	validates_presence_of :title
	

	#validate :check_valid_date  # if !self.project.nil?

	#private
	#def check_valid_date
	
	#	if (self.due_date < self.project.start_date || self.due_date > self.project.end_date)
	#		errors.add(:due_date, "is invalid")
	#	end
	#end

	#def check_boolean
	#	if !([true,false].include? self.is_completed)
	#		errors.add(:is_completed, "should be either true or false")
	#	end
	#end
	

	def details
		"#{self.title} - #{self.project_id} - #{self.due_date} - #{self.is_completed}"
	end
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :clients
	has_many :projects
	has_many :categories
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


	 def is_admin?
	 	return true if self.role == "admin"
	end
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	before_action :authenticate_user!
	load_and_authorize_resource
	def index
		if params[:status]
		@projects = current_user.projects.where('status = ?', params[:status])
	elsif params[:client_id]
		@projects = current_user.projects.where('client_id = ?', params[:client_id])
	else
		@projects = current_user.projects
	end



end

	def new
		@project = Project.new
		
	end
	def create
		@project = Project.new(project_params)
		@project.user_id = current_user.id
		if @project.save
			redirect_to projects_path notice: "Successfully created project"
		else
			render action: "new"
		end
	end
	def show
		@project = Project.find(params[:id])
		@task = Task.new
	end
	def edit
		@project = Project.find(params[:id])
	end
	def update
		@project = Project.find(params[:id])
		if @project.update_attributes(project_params)
			redirect_to project_path(@project.id), notice: "Successfully updated"
		else 
			render action: "edit"
		end
	end
	def destroy
		@project = Project.find(params[:id])
		@project.destroy
		redirect_to projects_path, notice: "Successfull deleted #{@project.name}"
	end


	private
	def project_params
		params[:project].permit(:client_id, :name, :description, :budget,:status, :start_date, :end_date, :status, :estimated_budget, category_ids: [])
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sandbox_helper.rb
module SandboxHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>


<% if @project.errors.any? %>
		<h4>These errors prohibited the form from being saved: </h4>
			<ul style="color:red;">
				<% @project.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
	<% end %>
	</ul>
<% end %>
	

	<div class="form-group">
	<label>Client</label><br/>
	<%= f.collection_select :client_id, current_user.clients, :id, :name, {prompt: "Select Client"}, {class: "form-control"} %><br/>
	</div>

	<div class="form-group">
	<label>Name</label><br/>
	<%= f.text_field :name, class: "form-control", required: true %><br/>
	</div>


	<div class="form-group">
	<label>Description</label><br/>
	<%= f.text_area :description, class: "form-control" %><br/>
	</div>



	<div class="form-group">
	<label>Start Date</label><br/>
	<%= f.date_field :start_date, order:[:day,:month,:year] %><br/>
	</div>

	<div class="form-group">
	<label>End Date</label><br/>
	<%= f.date_select :end_date, order:[:day,:month,:year] %><br/>
	</div>


	<div class="form-group">
	<label>Status</label><br/>
	
	<%# f.select :status, ["Name", "On-Going", "Completed"] %>
	<%= f.radio_button :status, "New" %> New
	<%= f.radio_button :status, "On-Going" %> On-Going
	<%= f.radio_button :status, "Completed" %> Completed
	<br/>
	</div>

	

	<div class="form-group">
	<label>Estimated Budget</label><br/>
	<%= f.number_field :budget, class: "form-control" %><br/>
	</div>


	<div class="form-group">
	<label>Select Categories </label><br/>
	<%= f.collection_check_boxes :category_ids, current_user.categories, :id, :name do |b| %>
	<%= b.check_box %>
	<%= b.label %>
	<br/>
	<% end %>
	</div>


	<%= f.submit "Submit", class: "btn btn-primary" %>

	<% end %>

app/views/projects/edit.html.erb
<h3> Edit Projects </h3>

<%= render 'form' %>

app/views/projects/index.html.erb
<div class="row">
	<div class="col-md-7">
			<div class="page header" >
			<h3> Listing Projects </h3>
			</div>
<b> Fileter by:
<%= link_to "New", projects_path(status: "New") %> |
<%= link_to "On-Going", projects_path(status: "On-Going") %> |
<%= link_to "Completed", projects_path(status: "Completed") %> |
<%= link_to "All", projects_path %>
</b>
<br/>

<b> Filter by:
<% current_user.clients.each do |client| %>
<%= link_to client.name, projects_path(client_id: client.id) %> |
<% end %>


<% if @projects.empty? %>
	<p>No Projects Found </p>
	<% else %>
	<table border="table table-stiped">
	<thead>
	<tr>
	<th>Name</th>
	<th>Client</th>
	<th>Start Date</th>
	<th>Description</th>
	<th>End Date</th>
	<th>Budget</th>
	<th>Actions</th>
	<th>Status</th>
	</tr>
	</thead>
	<% @projects.each do |project| %>
		<tr>
		<td><%= project.name %></td>
		<td><%= project.client.nil? ? "N/A" :project.client.name %></td>  
		<td><%= project.start_date.strftime("%A, %d %B %Y") %></td>
		<td><%= project.description %></td>
		<td><%= project.end_date.strftime("%A, %d %B %Y") %></td>
		<td><%= project.budget %></td>
		<td><%= link_to "Show", project_path(project.id) %>
		<td><%= project.status %></td>
		</tr>
		<% end %>
		<tbody>
		</tbody>
		<% end %>
		</table>

		<%= link_to "Add Project", new_project_path %>
</div>




<div class="col-md-5">
		<div class="page-header">
		<h3> Status </h3>
		</div>

		<%# data = { }
		data["new"] = @projects.where('status = ?', "New" ).size
		data["on-going"] = @projects.where('status = ?', "On-Going" ).size
		data["completed"] = @projects.where('status = ?', "Completed" ).size
		%>
		<%=
		data = {}
		statuses = @projects.pluck(:status).uniq
		statuses.each do |status|
		data[status] = @projects.where('status = ?', status).size
		end
		%> 
		<%= pie_chart(data) %>
		<%= column_chart(data) %>

		

		<h3> Tasks assigned to the project </h3>
		<%
		data = { }
		
		@projects.each do |project|
			data[project.name] =project.tasks.size
		end
		%>
		<%= column_chart(data) %>
		<%= pie_chart(data) %>

</div>

</div>

app/views/projects/new.html.erb
<h3> Add Projects </h3>

<%= render 'form' %>

app/views/projects/show.html.erb
<%= link_to "Export to Excel", project_path(@project.id , format: "xls") %>

<h3><%= @project.name %></h3>
<p><%= @project.description %> <%= @project.status %>
<%= link_to @project.client, client_path(@project.client_id) %></p>

(<%= @project.categories.pluck(:name).join(",") %>) 

<%= link_to "edit" , edit_project_path(@project.id) %> | 
<%= link_to "destroy", project_path(@project.id), data: {method: :delete, confirm: "Are you sure?"} %>


<% if @project.tasks.empty? %>
	No task Found
	<% else %>
		<h3> Total Tasks: <%= @project.tasks.size %></h3>
		<% task_completion = (@project.iscompleted_tasks.size / @project.tasks.size.to_f) * 100 %>
		<div class="progress">
  <div class="progress-bar progress-bar-success progress-bar-striped  " role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: <%=task_completion %>40%">
    <span class="sr-only">40% Complete (success)</span>
    <%= task_completion %>
  </div>
</div>





	<ul>
<% for task in @project.tasks %>
	<li><%= task.title %></li>
	<% end %>
	</ul>
	<% end %>


<h3> Completed Tasks </h3>
<% @project.iscompleted_tasks.each do |task| %>
	<li><%= task.title %></li>
	<% end %>


<h3> Incompleted Tasks </h3>
<ul>
<% @project.incompleted_tasks.each do |task| %>
<li>
<%= task.title %> -
<%= link_to "mark as Completed"	, tasks_mark_as_complete_path(task_id: task.id) %>
</li>
<% end %>
</ul>


<h3> Completed Tasks </h3>
<ul>
<% @project.iscompleted_tasks.each do |task| %>
<li>
<%= task.title %> -
<%= link_to "mark as InComplete"	, tasks_mark_as_incomplete_path(task_id: task.id) %>
</li>
<% end %>
</ul>		

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
 Add Task
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add Task</h4>
      </div>
      <div class="modal-body">
        <h3> Add Task </h3>
	<%= form_for @task do |f| %>
	<%= f.hidden_field :project_id, value: @project.id %>
	<label>Title </label><br/>
	<%= f.text_field :title %><br/>

	<label>Due Date</label><br/>
	<%= f.date_select :due_date, order:[:day,:month,:year] %><br/>

	<%= f.check_box :is_completed %> <label>Is Completed ?</label><br/>

	<%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>


	



<% data = { }
		
		data["completed"] = @project.tasks.where('is_completed = ?', true ).size
		data["incomplete"] = @project.tasks.where('is_completed = ?', false).size

		%>
		<%= pie_chart(data) %>
		

app/views/projects/show.xls.erb
<table border="1">
	<thead>
	<tr>
	<th>Name</th>
	<th>Client</th>
	<th>Start Date</th>
	<th>Description</th>
	<th>End Date</th>
	<th>Budget</th>
	<th>Actions</th>
	</tr>
	</thead>
	
		
		<td><%= @project.name %></td>
		<td><%= @project.client.nil? ? "N/A" :@project.client.name %></td>  
		<td><%= @project.start_date.strftime("%A, %d %B %Y") %></td>
		<td><%= @project.description %></td>
		<td><%= @project.end_date.strftime("%A, %d %B %Y") %></td>
		<td><%= @project.budget %></td>
		<td><%= link_to "Show", project_path(@project.id) %>
		</tr>
		
		

		<tbody>
		<% @project.tasks.each do |task| %>
		<tr>
		<td><%= task.title %></td>
		<td><%= task.due_date %></td>
		<td><%= task.is_completed ? "Yes" : "No" %></td>
		</tr>
		<% end %>
		</tbody>
		